### ISSUE TITLE
Suggestion: briefly explain type arguments (e.g. 'a) in functions and such

### ISSUE THREAD

**Issue by nlfiedler** [arecvlohe/reasonml-cheat-sheet#3]
From https://reasonml.github.io/docs/en/more-on-type it might be good to have an example of a function taking type arguments. I came across this with `state` in ReasonReact and asked myself "what is this magic?" until I figured out it was just type arguments. Thanks.

**Comment by arecvlohe** [comment]
@nlfiedler The explanation in the docs are okay but I found a good one here as well: https://medium.com/reasontraining/phantom-types-in-reasonml-1a4cfc18d999. I will look into adding an example.

**Comment by nlfiedler** [comment]
That is indeed a great explanation, thanks for sharing.

**Comment by arecvlohe** [comment]
I hope this helps 👉 11e83ef0cd7f543af477f69b8b30dd5762140d5a

**Comment by nlfiedler** [comment]
Terrific, thanks!
